import React, { useState, useMemo } from "react";
import { Truck, Calendar, IndianRupee, Gauge, Fuel, Percent, Download, Filter, CheckCircle2, AlertTriangle, Info, TrendingUp, MapPin, Clock, ArrowRight, Sparkles, Edit3, User, Wallet } from "lucide-react";
import { Vehicle, Trip, MaintenanceRecord, VehicleReportStats, Driver } from "../types";
import { calculateVehicleStats, calculateDriverStats, generateVehicleInsights, formatINR, formatIndianDate } from "../lib/calculations";
import { exportVehicleReportToCSV } from "../lib/exportCsv";
import { VehicleCharts } from "./VehicleCharts";
import { TripDetailsModal } from "./TripDetailsModal";
import { EditTripModal } from "./EditTripModal";

interface VehicleReportPageProps { vehicle: Vehicle; allVehicles: Vehicle[]; allTrips: Trip[]; allMaintenance: MaintenanceRecord[]; drivers?: Driver[]; onSelectVehicle: (vehicleId: string) => void; onDeleteTrip: (tripId: string) => Promise<void>; onUpdateTrip?: (tripId: string, tripData: Partial<Trip>) => Promise<void>; }

export const VehicleReportPage: React.FC<VehicleReportPageProps> = ({ vehicle, allVehicles, allTrips, allMaintenance, drivers = [], onSelectVehicle, onDeleteTrip, onUpdateTrip }) => {
  const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState("");
  const [appliedFromDate, setAppliedFromDate] = useState(""); const [appliedToDate, setAppliedToDate] = useState("");
  const [selectedDriverId, setSelectedDriverId] = useState(""); const [appliedDriverId, setAppliedDriverId] = useState("");
  const [activeTab, setActiveTab] = useState<"summary" | "charts" | "trips" | "insights">("summary");
  const [selectedTripForModal, setSelectedTripForModal] = useState<Trip | null>(null); const [editingTrip, setEditingTrip] = useState<Trip | null>(null);
  const handleQuickPreset = (preset: "all" | "thisMonth" | "last30" | "thisYear") => { const now=new Date(); if(preset==="all"){setFromDate("");setToDate("");setSelectedDriverId("");setAppliedFromDate("");setAppliedToDate("");setAppliedDriverId("");} else {const d=preset==="thisMonth"?new Date(now.getFullYear(),now.getMonth(),1):preset==="last30"?new Date(now.getTime()-30*86400000):new Date(now.getFullYear(),0,1);const s=d.toISOString().slice(0,10),t=now.toISOString().slice(0,10);setFromDate(s);setToDate(t);setAppliedFromDate(s);setAppliedToDate(t);}};
  const handleGenerateReport=(e:React.FormEvent)=>{e.preventDefault();setAppliedFromDate(fromDate);setAppliedToDate(toDate);setAppliedDriverId(selectedDriverId);};
  const selectedDriver=useMemo(()=>drivers.find(d=>d.id===appliedDriverId),[drivers,appliedDriverId]); const selectedDriverName=selectedDriver?.driver_name||"";
  const driverStats=useMemo(()=>!appliedDriverId&&!selectedDriverName?null:calculateDriverStats(appliedDriverId,selectedDriverName,allTrips,{from:appliedFromDate||undefined,to:appliedToDate||undefined}),[appliedDriverId,selectedDriverName,allTrips,appliedFromDate,appliedToDate]);
  const vehicleTrips=useMemo(()=>allTrips.filter(t=>t.vehicle_id===vehicle.id).filter(t=>(!appliedFromDate||t.trip_date>=appliedFromDate)&&(!appliedToDate||t.trip_date<=appliedToDate)).sort((a,b)=>b.trip_date.localeCompare(a.trip_date)),[allTrips,vehicle.id,appliedFromDate,appliedToDate]);
  const vehicleMaintenance=useMemo(()=>allMaintenance.filter(m=>m.vehicle_id===vehicle.id).filter(m=>(!appliedFromDate||m.maintenance_date>=appliedFromDate)&&(!appliedToDate||m.maintenance_date<=appliedToDate)).sort((a,b)=>b.maintenance_date.localeCompare(a.maintenance_date)),[allMaintenance,vehicle.id,appliedFromDate,appliedToDate]);
  const stats:VehicleReportStats=useMemo(()=>calculateVehicleStats(vehicle.id,vehicle.vehicle_number,vehicleTrips,vehicleMaintenance),[vehicle.id,vehicle.vehicle_number,vehicleTrips,vehicleMaintenance]);
  const totalHaltingDays=useMemo(()=>vehicleTrips.reduce((total,t)=>total+(t.loading_halting_days!==undefined||t.unloading_halting_days!==undefined?(Number(t.loading_halting_days)||0)+(Number(t.unloading_halting_days)||0):(Number(t.halting_days)||0)),0),[vehicleTrips]);
  const totalHaltingCharges=useMemo(()=>vehicleTrips.reduce((total,t)=>total+(t.loading_halting_fare!==undefined||t.unloading_halting_fare!==undefined?(Number(t.loading_halting_fare)||0)+(Number(t.unloading_halting_fare)||0):(Number(t.halting_fare)||0)),0),[vehicleTrips]);
  const overallProfit=stats.finalVehicleProfit+totalHaltingCharges;
  const insights=useMemo(()=>generateVehicleInsights(stats,vehicleTrips,vehicleMaintenance),[stats,vehicleTrips,vehicleMaintenance]);
  const handleExportCSV=()=>exportVehicleReportToCSV(vehicle.vehicle_number,vehicleTrips,vehicleMaintenance,stats);

  return (<div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-10 space-y-8">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-6 rounded-3xl border border-slate-200 shadow-xs"><div className="flex items-center gap-4"><div className="w-14 h-14 rounded-2xl bg-blue-600 text-white flex items-center justify-center shadow-md shadow-blue-600/25"><Truck className="w-8 h-8"/></div><div><h1 className="text-2xl sm:text-3xl font-black font-mono tracking-tight text-slate-900">{vehicle.vehicle_number}</h1><p className="text-xs sm:text-sm text-slate-500 mt-0.5">Dedicated Vehicle Report &amp; Performance Analytics</p></div></div><div className="flex flex-wrap items-center gap-3"><select value={vehicle.id} onChange={e=>onSelectVehicle(e.target.value)} className="px-3 py-2 rounded-xl border border-slate-300 font-mono text-sm bg-white font-bold text-slate-800">{allVehicles.map(v=><option key={v.id} value={v.id}>{v.vehicle_number}</option>)}</select><button onClick={handleExportCSV} className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-slate-900 text-white text-xs font-bold"><Download className="w-4 h-4"/>Export CSV</button></div></div>
    <div className="bg-slate-900 text-white p-6 rounded-3xl shadow-xl border border-slate-800"><form onSubmit={handleGenerateReport} className="space-y-4"><div className="flex flex-wrap items-center gap-2"><Filter className="w-4 h-4 text-blue-400"/><span className="text-sm font-bold">Select Date Range</span><button type="button" onClick={()=>handleQuickPreset("all")}>All Time</button><button type="button" onClick={()=>handleQuickPreset("thisMonth")}>This Month</button><button type="button" onClick={()=>handleQuickPreset("last30")}>Last 30 Days</button><button type="button" onClick={()=>handleQuickPreset("thisYear")}>This Year</button></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/><input type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/><select value={selectedDriverId} onChange={e=>setSelectedDriverId(e.target.value)}><option value="">All Drivers (Fleet Combined)</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.driver_name}</option>)}</select><button type="submit" className="py-2.5 px-4 rounded-xl bg-blue-600 text-white font-bold">Generate Report <ArrowRight className="inline w-4 h-4"/></button></div></form></div>
    <div className="bg-slate-50 rounded-3xl border border-slate-200 p-5"><h2 className="text-xl font-black text-slate-900 mb-5">Vehicle Performance Snapshot</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Total Trips</div><div className="text-2xl sm:text-3xl font-black font-mono mt-1">{stats.totalTrips}</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Total Revenue</div><div className="text-2xl sm:text-3xl font-black font-mono text-emerald-700 mt-1">{formatINR(stats.totalTripRevenue)}</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Total Expenses</div><div className="text-2xl sm:text-3xl font-black font-mono text-red-700 mt-1">{formatINR(stats.totalExpenses)}</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Final Net Profit</div><div className="text-2xl sm:text-3xl font-black font-mono text-emerald-700 mt-1">{formatINR(stats.finalVehicleProfit)}</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Total running distance</div><div className="text-2xl sm:text-3xl font-black font-mono mt-1">{stats.overallTripRunningKms} KM</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Total Toll Charges</div><div className="text-2xl sm:text-3xl font-black font-mono mt-1">{formatINR(stats.overallTollCharges)}</div><div className="text-xs text-slate-500 mt-1">Highway &amp; FASTag tolls</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Overall Total Diesel</div><div className="text-2xl sm:text-3xl font-black font-mono mt-1">{stats.overallDieselLitres} L</div><div className="text-xs text-slate-500 mt-1">Total fuel cost: {formatINR(stats.overallDieselExpense)}</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Average Mileage</div><div className="text-2xl sm:text-3xl font-black font-mono text-amber-700 mt-1">{stats.overallMileage} km/L</div><div className="text-xs text-slate-500 mt-1">Running KMs / Diesel Litres</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Service Maintenance</div><div className="text-2xl sm:text-3xl font-black font-mono text-amber-600 mt-1">{formatINR(stats.overallMaintenanceAmount)}</div><div className="text-xs text-slate-500 mt-1">{vehicleMaintenance.length} service records</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1"><Clock className="w-3.5 h-3.5 text-violet-600"/>Total Halting Days</div><div className="text-2xl sm:text-3xl font-black font-mono text-violet-700 mt-1">{totalHaltingDays} Days</div><div className="text-xs text-slate-500 mt-1">Loading + Unloading halting</div></div>
      <div className="bg-white p-5 rounded-2xl border border-slate-200"><div className="text-xs font-bold text-slate-500 uppercase">Total Halting Charges</div><div className="text-2xl sm:text-3xl font-black font-mono text-rose-700 mt-1">{formatINR(totalHaltingCharges)}</div><div className="text-xs text-slate-500 mt-1">Total loading + unloading halting</div></div>
      <div className="bg-white p-5 rounded-2xl border-2 border-violet-500/80 bg-violet-50/20"><div className="text-xs font-bold text-violet-800 uppercase">Overall Profit</div><div className={`text-2xl sm:text-3xl font-black font-mono mt-1 ${overallProfit>=0?"text-violet-700":"text-red-700"}`}>{formatINR(overallProfit)}</div><div className="text-xs text-violet-700 font-semibold mt-1">Final Net Profit + Total Halting Charges</div></div>
    </div></div>
    <div className="flex border-b border-slate-200 space-x-1 sm:space-x-4"><button onClick={()=>setActiveTab("summary")} className="py-3 px-3 sm:px-5 font-bold text-sm">Detailed Financial Statement</button><button onClick={()=>setActiveTab("charts")} className="py-3 px-3 sm:px-5 font-bold text-sm">Visual Charts &amp; Trends</button><button onClick={()=>setActiveTab("trips")} className="py-3 px-3 sm:px-5 font-bold text-sm">Trip History ({vehicleTrips.length})</button><button onClick={()=>setActiveTab("insights")} className="py-3 px-3 sm:px-5 font-bold text-sm">Business Insights ({insights.length})</button></div>
    {activeTab==="summary"&&<div className="bg-white p-6 rounded-3xl border border-slate-200"><h3 className="text-lg font-bold">Full Income &amp; Expense Statement for {vehicle.vehicle_number}</h3><p className="text-sm text-slate-500 mt-2">Detailed financial statement based on the selected vehicle and date range.</p></div>}
    {activeTab==="charts"&&<VehicleCharts stats={stats} trips={vehicleTrips}/>} {activeTab==="trips"&&<div className="space-y-3">{vehicleTrips.map(t=><div key={t.id} className="bg-white p-4 rounded-2xl border border-slate-200"><div className="font-bold">{formatIndianDate(t.trip_date)} — {t.from_city} to {t.to_city}</div><div className="text-sm text-slate-500">{t.vehicle_number||vehicle.vehicle_number} · {t.driver_name||""}</div></div>)}</div>} {activeTab==="insights"&&<div className="space-y-3">{insights.map((i,idx)=><div key={idx} className="bg-white p-4 rounded-2xl border border-slate-200">{typeof i === "string" ? i : JSON.stringify(i)}</div>)}</div>}
    {selectedTripForModal&&<TripDetailsModal trip={selectedTripForModal} onClose={()=>setSelectedTripForModal(null)}/>} {editingTrip&&onUpdateTrip&&<EditTripModal trip={editingTrip} onClose={()=>setEditingTrip(null)} onUpdate={onUpdateTrip}/>} 
  </div>);
};
